# NCP Configuration
# Made by rollermachine
# For The Enchanted Network

savebackconfig: true
configversion:
  notify: true
  notifymaxpaths: 5
  created: 1104
  saved: 1104
logging:
  active: true
  maxqueuesize: 5000
  extended:
    status: false
    commands:
      actions: false
    allviolations:
      debug: true
      debugonly: false
      backend:
        trace: false
        notify: false
  backend:
    console:
      active: true
      asynchronous: true
    file:
      active: true
      prefix: ''
      filename: nocheatplus.log
    ingamechat:
      active: true
      prefix: '&c»&4&l Guardian &c« &f'
      subscriptions: false
data:
  expiration:
    active: false
    duration: 60
    history: false
  consistencychecks:
    active: true
    interval: 10
    maxtime: 2
    suppresswarnings: false
protection:
  plugins:
    hide:
      active: true
      nopermission:
        message: '&cI''m sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.'
        commands:
        - plugins
        - version
        - icanhasbukkit
      unknowncommand:
        message: Unknown command. Type "/help" for help.
        commands: []
  commands:
    consoleonly:
      active: false
      message: '&cI''m sorry, but this command can''t be executed in chat. Use the console instead!'
      commands:
      - op
      - deop
  clients:
    motd:
      active: true
      allowall: false
checks:
  blockbreak:
    direction:
      active: true
      actions: vl>20 cmd:guardianban
    fastbreak:
      active: true
      strict: true
      delay: 100
      intervalsurvival: 100
      grace: 2000
      actions: vl>10 cmd:guardianban
    frequency:
      active: true
      intervalcreative: 95
      intervalsurvival: 45
      shortterm:
        ticks: 5
        limit: 7
      actions: vl>15 cmd:guardianban
    noswing:
      active: true
      actions: vl>15 cmd:guardianban
    reach:
      active: true
      actions: vl>7 cmd:guardianban
    wrongblock:
      active: true
      level: 10
      actions: vl>50 cmd:guardianban
  blockinteract:
    direction:
      active: true
      actions: vl>25 cmd:guardianban
    reach:
      active: true
      actions: vl>5 cmd:guardianban
    speed:
      active: true
      interval: 2000
      limit: 60
      actions: vl>1500 cmd:guardianban
    visible:
      active: true
      actions: vl>100 cmd:guardianban
  blockplace:
    against:
      active: true
      actions:
    autosign:
      active: true
      skipempty: false
      actions: vl>10 cmd:guardianban
    direction:
      active: true
      actions: vl>25 cmd:guardianban
    fastplace:
      active: true
      limit: 22
      shortterm:
        ticks: 10
        limit: 6
      actions: vl>200 cmd:guardianban
    reach:
      active: true
      actions: vl>10 cmd:guardianban
    noswing:
      active: true
      exceptions:
      - WATER_LILY
      - FLINT_AND_STEEL
      actions: vl>10 cmd:guardianban
    speed:
      active: true
      interval: 45
      actions: vl>200 cmd:guardianban
    preventmisc:
      boatsanywhere: true
  chat:
    captcha:
      active: false
      skip:
        commands: false
      characters: abcdefghjkmnpqrtuvwxyzABCDEFGHJKMNPQRTUVWXYZ2346789
      length: 6
      question: '&cPlease type ''&6[captcha]&c'' to continue sending messages/commands.'
      success: '&aOK, it sounds like you''re not a spambot.'
      tries: 3
      actions: cancel cmd:kickcaptcha vl>4 log:captcha:2:5:cf cancel cmd:kickcaptcha
    color:
      active: true
      actions: log:color:0:1:if cancel
    commands:
      active: true
      exclusions: []
      handleaschat:
      - me
      level: 10
      shortterm:
        ticks: 18
        level: 3
      actions: log:commands:0:5:cf cancel cmd:kickcommands vl>20 log:commands:0:5:cf cancel cmd:tempkick1
    text:
      active: true
      allowvlreset: true
      frequency:
        normal:
          minimum: 0.0
          factor: 0.9
          weight: 6
          level: 160
          actions: cancel cmd:tellchatnormal vl>7 log:chatnormal:0:5:f cancel cmd:tellchatnormal vl>20 log:chatnormal:0:5:cf cancel cmd:kickchatnormal vl>40 log:chatnormal:0:5:cf cancel cmd:kickchat5
        shortterm:
          minimum: 2.0
          factor: 0.7
          weight: 3.0
          level: 20.0
          actions: log:chatfast:0:5:cf cancel cmd:kickchatfast vl>20 log:chatfast:0:5:cf cancel cmd:kickchat1 vl>40 log:chatfast:0:5:cf cancel cmd:kickchat5
      message:
        lettercount: 1.0
        partition: 1.0
        uppercase: 1.0
        afterjoin: 1.5
        nomoving: 1.5
        repeatviolation: 1.0
        repeatglobal: 1.0
        repeatself: 1.5
        words:
          lengthav: 1.0
          lengthmsg: 1.0
          noletter: 0.0
      global:
        active: true
        weight: 1.0
        words:
          active: false
        prefixes:
          active: false
        similarity:
          active: false
      player:
        active: true
        words:
          active: false
        prefixes:
          active: false
        similarity:
          active: false
    warning:
      active: true
      level: 67
      message: |-
        &e>>>
        &e>>> &cPlease &eslow down &cchat, &eyou might get kicked &cfor spam.
        &e>>>
      timeout: 10
    relog:
      active: true
      timeout: 5000
      warning:
        message: '&cYou relogged really fast! If you keep doing that, you''re going to be banned.'
        number: 1
        timeout: 60000
      kickmessage: You logged in too fast, take a chill pill.
      actions: log:relog:0:10:cf cancel vl>20 log:relog:0:10:cf cancel cmd:tempkick5
    logins:
      active: true
      startupdelay: 600
      perworldcount: false
      seconds: 10
      limit: 10
      kickmessage: Too many people logging in, retry soon.
  combined:
    bedleave:
      active: true
      actions: vl>10 cmd:guardianban
    enderpearl:
      active: true
      preventclickblock: true
    improbable:
      active: true
      level: 300
      actions: vl>10 cmd:guardianban
    invulnerable:
      active: true
      triggers:
        always: false
        falldistance: true
      initialticks:
        join: -1
      ignore:
      - FALL
      modifiers:
        all: 0
    munchhausen:
      active: false
      actions: cancel vl>100 cancel log:munchhausen:0:60:if
    yawrate:
      rate: 380
      penalty:
        factor: 1.0
        minimum: 250
        maximum: 2000
      improbable: true
  fight:
    canceldead: true
    toolchangepenalty: 500
    pvp:
      knockbackvelocity: default
    yawrate:
      active: true
    angle:
      active: true
      threshold: 50
      actions: vl>100 cmd:guardianban
    critical:
      active: true
      cancel:
        cancel: 100
        dividedamage: 1.5
      falldistance: 0.06251
      actions: vl>5 cmd:guardianban
    direction:
      active: true
      strict: false
      penalty: 500
      actions: vl>10 cmd:guardianban
    fastheal:
      active: true
      interval: 4000
      buffer: 1000
      actions: vl>10 cmd:guardianban
    godmode:
      active: true
      minage: 1100
      maxage: 5000
      actions: vl>50 cmd:guardianban
    noswing:
      active: true
      actions: vl>10 cmd:guardianban
    reach:
      active: true
      survivaldistance: 4.4
      penalty: 500
      reduce: true
      reducedistance: 0.9
      reducestep: 0.15
      actions: vl>10 cmd:guardianban
    selfhit:
      active: true
      actions: vl>5 cmd:guardianban
    speed:
      active: true
      limit: 15
      actions: vl>60 cmd:guardianban
      shortterm:
        ticks: 7
        limit: 6
  inventory:
    drop:
      active: true
      limit: 100
      timeframe: 20
      actions: cancel
    fastclick:
      active: true
      sparecreative: true
      tweaks1_5: true
      limit:
        shortterm: 4
        normal: 15
      actions: vl>50 cmd:guardianban
    instantbow:
      active: true
      strict: true
      delay: 130
      improbable:
        feedonly: false
        weight: 0.6
      actions: vl>10 cmd:guardianban
    instanteat:
      active: true
      actions: vl>3 cmd:guardianban
    fastconsume:
      active: true
      duration: 0.7
      whitelist: false
      items: []
      actions: vl>3 cmd:guardianban
    gutenberg:
      active: true
      actions: vl>10 cmd:guardianban
    items:
      active: true
    open:
      active: true
      close: true
      cancelother: true
    hotfix:
      duplication:
        fallingblockendportal: true
  moving:
    creativefly:
      active: true
      ignoreallowflight: true
      ignorecreative: false
      model:
        creative:
          horizontal:
            speed: 100
          vertical:
            ascend:
              speed: 100
            maxheight: 128
        spectator:
          horizontal:
            speed: 450
          vertical:
            ascend:
              speed: 170
            maxheight: 128
          gravity: false
          ground: false
        levitation:
          horizontal:
            speed: 50
          vertical:
            ascend:
              speed: 10
            maxheight: 128
            gravity: false
          modifiers: false
          gravity: false
          ground: false
        elytra:
          horizontal:
            speed: 520
            modsprint: 1.0
          vertical:
            ascend:
              speed: 0
            maxheight: 128
          modifiers: false
      actions: vl>50 cmd:guardianban
    morepackets:
      active: true
      seconds: 6
      epsideal: 20
      epsmax: 22
      burst:
        packets: 40
        directviolation: 60
        epmviolation: 180
      setbackage: 40
      actions: vl>100 cmd:guardianban
    nofall:
      active: true
      dealdamage: true
      skipallowflight: true
      resetonviolation: false
      resetonteleport: false
      resetonvehicle: true
      anticriticals: true
      actions: vl>10 cmd:guardianban
    passable:
      active: true
      actions: vl>100 cmd:guardianban
      untracked:
        teleport:
          active: true
        command:
          active: true
          tryteleport: true
          prefixes:
          - sethome
          - home set
          - setwarp
          - warp set
          - setback
          - set back
          - back set
    survivalfly:
      active: true
      extended:
        vertical-accounting: true
      stepheight: default
      hbufmax: 1.0
      setbackpolicy:
        falldamage: true
        voidtovoid: true
      actions: vl>2000 cmd:guardianban
      hover:
        active: true
        step: 5
        ticks: 85
        loginticks: 60
        falldamage: true
        sfviolation: 500
    velocity:
      activationcounter: 80
      activationticks: 140
      strictinvalidation: true
    splitmoves: default
    ignorestance: default
    tempkickillegal: true
    loadchunks:
      join: true
      move: true
      teleport: true
      worldchange: true
    sprintinggrace: 2.0
    assumesprint: true
    speedgrace: 4.0
    enforcelocation: default
    setback:
      method: default
    vehicle:
      preventdestroyown: true
      enforcelocation: default
      schedulesetbacks: default
      morepackets:
        active: true
        actions: vl>30 cmd:guardianban
      envelope:
        active: default
        actions: vl>100 cmd:guardianban
    message:
      illegalplayermove: Illegal move.
      illegalvehiclemove: Illegal vehicle move.
  net:
    attackfrequency:
      active: true
      limitforseconds:
        half: 10
        one: 15
        two: 30
        four: 60
        eight: 100
      actions: vl>25 cmd:guardianban
    flyingfrequency:
      active: true
      seconds: 5
      packetspersecond: 60
      actions: cancel
      reduceredundant:
        active: true
        seconds: 3
        actions: cancel
    keepalivefrequency:
      active: true
      actions: vl>10 cmd:guardianban
    packetfrequency:
      active: default
      limitpersecond: 200
      seconds: 4
      actions: vl>10 cmd:guardianban
    sounddistance:
      active: true
      maxdistance: 320
    superseded:
      flying:
        cancelwaiting: true
strings:
  angle: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  attackfrequency: '&c&l(!) &r&c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  ban: ban [player]
  ban-ip: ban-ip [ip]
  bautosign: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  bbfrequency: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  bdirection: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  bedleave: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  bpspeed: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  breach: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  bspeed: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  bvisible: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  bwrong: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  captcha: ' &c[player] &7failed captcha repeatedly &8(&c[violations]VL&8)'
  chatnormal: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  color: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  commands: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  combspeed: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  critical: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  drop: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  dropkick: ncp delay ncp kick [player] Dropping items too fast.
  fastbreak: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  fastclick: ' r&c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  fastconsume: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  fastheal: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  fastplace: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  fdirection: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  flyshort: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  flylong: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  flyfile: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  freach: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  fselfhit: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  fspeed: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  gutenberg: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  godmode: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  improbable: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  instantbow: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  instanteat: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  keepalive: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  guardianban: acban [player]
  kick: kick [player]
  kickalive: ncp kick [player] Too many keep-alive packets.
  kickattackfrequency: ncp kick [player] Unlikely fast clicking.
  kickbedleave: ncp delay ncp kick [player] Go find a bed!
  kickbspeed: ncp kick [player] You interacted too fast!
  kickcaptcha: ncp kick [player] Enter the captcha!
  kickchat1: ncp tempkick [player] 1 You're still not allowed to spam!
  kickchat5: ncp tempkick [player] 5 You're not intended to spam!
  kickchatfast: ncp kick [player] You're not allowed to spam in chat!
  kickchatnormal: ncp kick [player] Too many chat messages, take a break.
  kickcommands: ncp tempkick [player] 1 You're not allowed to spam commands!
  kickfly: ncp delay ncp kick [player] Kicked for flying (or related)
  kickfrequency: ncp kick [player] You did something too fast!
  kickgod: ncp kick [player] God mode?
  kickinvaliddata: ncp kick [player] Invalid data.
  kickpacketfrequency: ncp kick [player] Too many packets.
  kickpackets: ncp delay ncp kick [player] Too many packets (extreme lag?)
  kickselfhit: ncp kick [player] You tried to hit yourself!
  kickwb: ncp kick [player] Block breaking out of sync!
  knockback: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  morepackets: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  msgtempdenylogin: You are temporarily denied to join this server.
  munchhausen: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  nofall: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  chatfast: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  noswing: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  passable: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  relog: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
  tellchatnormal: 'ncp tell [player] &cNCP: &eToo many messages, slow down...'
  tempkick1: ncp tempkick [player] 1 Wait a minute!
  tempkick5: ncp tempkick [player] 5 You have five minutes to think about it!
  vehicleenvelope: ' &c[player] &7failed &c[check] &8(&c[violations]VL&8)'
compatibility:
  managelisteners: false
  exemptions:
    wildcard:
      default:
        metadata:
          active: true
          keys:
          - nocheat.exempt
      npc:
        active: true
        bukkitnpc: true
        metadata:
          active: true
          keys:
          - NPC
    remove:
      join: true
      leave: true
  server:
    cbdedicated:
      enable: true
    cbreflect:
      enable: true
  blocks:
    allowinstantbreak: []
    overrideflags:
      snow: default
      piston_moving_piece: default+ign_passable+ground_height
    changetracker:
      active: true
      pistons: true
      maxageticks: 80
      perworld:
        maxentries: 1000
