command /clearchat:
    permission: chat.clearchat
    permission message: You don't have permission
    usage: &c/clearchat
    trigger:
        loop 250 times:
            broadcast ""
        broadcast "&aChat has been cleared by &b&l%player%"

command /cc:
    permission: chat.clearchat
    permission message: You don't have permission
    usage: &c/cc
    trigger:
        loop 250 times:
            broadcast ""
        broadcast "&aChat has been cleared by &b&l%player%"
