on join:
    broadcast "&8[&a+&8] &b%player%"
    send "&cWelcome back &b&l%player%"
    send "&cThe current gamemode is: &b&lSkyWars"
    send "&cDo &b&l/help &cfor a list of commands and more information"
    make console execute "/effect %player% clear"
    if player is op:
        send "&4&lAttention &b» &cDe-OP yourself for correct color coding in &b&lChat&c!"
on disconnect:
    broadcast "&8[&a-&8] &b%player%"

on first join:
    broadcast "&8[&aNEW&8] &b%player%"
