options:
  permission: admin.kills
  prefix: &7You got a &3point

#Add the skywars maps name after the worlds! Put a # before them if they're not set.

  world1: SkyWarsArenaWorld
  #world2:
  #world3:
  #world4:
  #world5:
  #world6:




on kill in @world1 or @world2 or @world3 or @world4 or @world5 or @world6:
  add 1 to {_skywars.point::%player%}
  add 1 to {_exp::%player%}



every second:
  loop all players:
    if {_exp::%loop-player%} is 100:
      add 1 to {_level::%player%}
